# Generated by Django 5.2.7 on 2025-11-11 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Major Activity Name')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text="The total weight of this major activity. Detail activities' weights must sum up to this value.", max_digits=5, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget for this major activity and all its sub-tasks.', max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Detail Activity Description')),
                ('weight', models.DecimalField(decimal_places=2, help_text="Weight share of the Major Activity's total weight.", max_digits=5)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text="Budget allocated to this detail activity (a portion of the Major Activity's total budget).", max_digits=12, null=True)),
                ('responsible_person', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('major_activity', models.ForeignKey(help_text='The major activity this detail activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='detail_activities', to='plans.majoractivity')),
            ],
            options={
                'verbose_name_plural': 'Detail Activities',
                'ordering': ['major_activity', 'weight'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('individual', 'Individual'), ('department', 'Department'), ('corporate', 'Corporate')], max_length=20)),
                ('plan_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'July'), (2, 'August'), (3, 'September'), (4, 'October'), (5, 'November'), (6, 'December'), (7, 'January'), (8, 'February'), (9, 'March'), (10, 'April'), (11, 'May'), (12, 'June')], null=True)),
                ('quarter_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of budgets from all Major Activities, updated upon save/edit.', max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='majoractivity',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_activities', to='plans.plan'),
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement', models.CharField(blank=True, help_text='e.g., Percentage, Count', max_length=255, null=True)),
                ('baseline', models.FloatField()),
                ('target', models.FloatField()),
                ('target_q1', models.FloatField(default=0.0)),
                ('target_q2', models.FloatField(default=0.0)),
                ('target_q3', models.FloatField(default=0.0)),
                ('target_q4', models.FloatField(default=0.0)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plans.plan')),
            ],
        ),
    ]
