# Generated by Django 5.2.6 on 2025-11-06 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('individual', 'Individual'), ('department', 'Department'), ('corporate', 'Corporate')], max_length=20)),
                ('plan_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'July'), (2, 'August'), (3, 'September'), (4, 'October'), (5, 'November'), (6, 'December'), (7, 'January'), (8, 'February'), (9, 'March'), (10, 'April'), (11, 'May'), (12, 'June')], null=True)),
                ('quarter_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement', models.CharField(blank=True, help_text='e.g., Percentage, Count', max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('baseline', models.FloatField()),
                ('target', models.FloatField()),
                ('target_q1', models.FloatField(default=0.0)),
                ('target_q2', models.FloatField(default=0.0)),
                ('target_q3', models.FloatField(default=0.0)),
                ('target_q4', models.FloatField(default=0.0)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_activity', models.CharField(max_length=255)),
                ('detail_activity', models.TextField()),
                ('responsible_person', models.CharField(max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plans.plan')),
            ],
        ),
    ]
