# Generated by Django 6.0.1 on 2026-01-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='current_reviewer_role',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='pillar',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate'), ('state-minister-destination', 'State Minister - Destination'), ('state-minister-promotion', 'State Minister - Promotion')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='detailactivity',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='level',
            field=models.CharField(choices=[('individual', 'Individual'), ('desk', 'Desk'), ('department', 'Department'), ('corporate', 'Corporate'), ('state-minister-destination', 'State Minister - Destination'), ('state-minister-promotion', 'State Minister - Promotion'), ('strategic-team', 'Strategic Team'), ('minister', 'Minister')], max_length=40),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
