# Generated by Django 5.2.6 on 2025-11-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='total_budget',
        ),
        migrations.AlterField(
            model_name='detailactivity',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated for this detail activity.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total budget for this major activity and all its sub-tasks.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_activities', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The total weight of this major activity. Detail activities' weights must sum up to this value (e.g., 20.00).", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8'), (9, 'Week 9'), (10, 'Week 10'), (11, 'Week 11'), (12, 'Week 12'), (13, 'Week 13'), (14, 'Week 14'), (15, 'Week 15'), (16, 'Week 16'), (17, 'Week 17'), (18, 'Week 18'), (19, 'Week 19'), (20, 'Week 20'), (21, 'Week 21'), (22, 'Week 22'), (23, 'Week 23'), (24, 'Week 24'), (25, 'Week 25'), (26, 'Week 26'), (27, 'Week 27'), (28, 'Week 28'), (29, 'Week 29'), (30, 'Week 30'), (31, 'Week 31'), (32, 'Week 32'), (33, 'Week 33'), (34, 'Week 34'), (35, 'Week 35'), (36, 'Week 36'), (37, 'Week 37'), (38, 'Week 38'), (39, 'Week 39'), (40, 'Week 40'), (41, 'Week 41'), (42, 'Week 42'), (43, 'Week 43'), (44, 'Week 44'), (45, 'Week 45'), (46, 'Week 46'), (47, 'Week 47'), (48, 'Week 48'), (49, 'Week 49'), (50, 'Week 50'), (51, 'Week 51'), (52, 'Week 52')], null=True),
        ),
    ]
