# Generated by Django 5.2.6 on 2025-11-07 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='weight',
        ),
        migrations.CreateModel(
            name='MajorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Major Activity Name')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text="The total weight of this major activity. Detail activities' weights must sum up to this value.", max_digits=5, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget for this major activity and all its sub-tasks.', max_digits=12, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_activities', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Detail Activity Description')),
                ('weight', models.DecimalField(decimal_places=2, help_text="Weight share of the Major Activity's total weight.", max_digits=5)),
                ('responsible_person', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('major_activity', models.ForeignKey(help_text='The major activity this detail activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='detail_activities', to='plans.majoractivity')),
            ],
            options={
                'verbose_name_plural': 'Detail Activities',
                'ordering': ['major_activity', 'weight'],
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
