# Generated by Django 5.2.6 on 2025-09-10 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='monthly_plan',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='monthly_plan',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='monthly_plan',
        ),
        migrations.RemoveField(
            model_name='quarterlyplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='quarterly_plan',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='quarterly_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='quarterly_plan',
        ),
        migrations.RemoveField(
            model_name='report',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='weekly_plan',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='weekly_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='weekly_plan',
        ),
        migrations.RemoveField(
            model_name='yearlyplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='yearly_plan',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='yearly_plan',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='yearly_plan',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='accountable_person',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='strategicgoal',
            name='description',
        ),
        migrations.AlterField(
            model_name='kpi',
            name='baseline',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('individual', 'Individual'), ('department', 'Department'), ('corporate', 'Corporate')], max_length=20)),
                ('plan_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Month 1'), (2, 'Month 2'), (3, 'Month 3'), (4, 'Month 4'), (5, 'Month 5'), (6, 'Month 6'), (7, 'Month 7'), (8, 'Month 8'), (9, 'Month 9'), (10, 'Month 10'), (11, 'Month 11'), (12, 'Month 12')], null=True)),
                ('quarter_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='strategicgoal',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plans.plan'),
        ),
        migrations.DeleteModel(
            name='MonthlyPlan',
        ),
        migrations.DeleteModel(
            name='QuarterlyPlan',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
        migrations.DeleteModel(
            name='YearlyPlan',
        ),
    ]
