# Generated by Django 5.2.8 on 2025-11-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailactivity',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='majoractivity',
            name='total_weight',
        ),
        migrations.AlterField(
            model_name='detailactivity',
            name='detail_activity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detailactivity',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='measurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Allocated budget for this Major Activity.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='major_activity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
