# Generated by Django 6.0.1 on 2026-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_current_reviewer_role_plan_pillar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pillar', models.CharField(choices=[('corporate', 'Corporate'), ('state-minister-destination', 'State Minister - Destination'), ('state-minister-promotion', 'State Minister - Promotion')], max_length=40)),
            ],
        ),
    ]
