# Generated by Django 5.2.6 on 2025-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_kpi_monthly_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='goal',
        ),
        migrations.AlterField(
            model_name='plan',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'July'), (2, 'August'), (3, 'September'), (4, 'October'), (5, 'November'), (6, 'December'), (7, 'January'), (8, 'February'), (9, 'March'), (10, 'April'), (11, 'May'), (12, 'June')], null=True),
        ),
    ]
