# Generated by Django 5.2.6 on 2025-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department of the user (e.g., Marketing, IT)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CORPORATE', 'corporate'), ('DEPARTMENT', 'Department'), ('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=20),
        ),
    ]
