# Generated by Django 5.2 on 2025-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CORPORATE', 'Corporate'), ('STRATEGIC-TEAM', 'Strategic-Team'), ('MD', 'MD'), ('DEPARTMENT', 'Department'), ('DESK', 'Desk'), ('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=20),
        ),
    ]
