# Generated by Django 6.0.1 on 2026-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('desk', 'Desk'), ('department', 'Department'), ('corporate', 'Corporate'), ('strategic-team', 'Strategic Team'), ('state-minister-destination', 'State Minister - Destination'), ('state-minister-promotion', 'State Minister - Promotion'), ('minister', 'Minister')], default='individual', max_length=40),
        ),
    ]
