# Generated by Django 6.0.1 on 2026-01-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('desk', 'Desk'), ('department', 'Department'), ('corporate', 'Corporate'), ('state-minister-destination', 'State Minister - Destination'), ('state-minister-promotion', 'State Minister - Promotion'), ('strategic-team', 'Strategic Team'), ('minister', 'Minister')], default='individual', max_length=40),
        ),
    ]
