# Generated by Django 6.0.1 on 2026-01-08 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, help_text='Completion percentage', max_digits=5)),
                ('actual_budget_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('challenge', models.TextField(blank=True, null=True)),
                ('mitigation', models.TextField(blank=True, null=True)),
                ('major_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.majoractivity')),
            ],
        ),
        migrations.CreateModel(
            name='DetailActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('detail_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.detailactivity')),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_reports', to='reports.majoractivityreport')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('overall_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='majoractivityreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to='reports.report'),
        ),
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.FloatField()),
                ('achievement_percent', models.FloatField(help_text='Calculated %')),
                ('remark', models.TextField(blank=True, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.kpi')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_reports', to='reports.report')),
            ],
        ),
    ]
