# Generated by Django 5.2.6 on 2025-09-10 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_remove_kpi_monthly_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('goal_title', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('baseline_value', models.FloatField(default=0.0)),
                ('target_value', models.FloatField(default=0.0)),
                ('achieved_value', models.FloatField(default=0.0)),
                ('budget_planned', models.FloatField(default=0.0)),
                ('budget_used', models.FloatField(default=0.0)),
                ('performance', models.FloatField(default=0.0)),
                ('difference', models.FloatField(default=0.0)),
                ('responsible_body', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='plans.strategicgoal')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='plans.kpi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='plans.plan')),
            ],
        ),
    ]
