# Generated by Django 6.0.1 on 2026-01-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpireport',
            name='achievement_percent',
            field=models.FloatField(default=0, help_text='Calculated %'),
        ),
        migrations.AlterField(
            model_name='kpireport',
            name='actual_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
