# Generated by Django 6.0.1 on 2026-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_kpireport_achievement_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoractivityreport',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Completion percentage', max_digits=5, null=True),
        ),
    ]
